version: 2.1
jobs:
  build:
    docker:
      - image: maven:3.6-jdk-12
    steps:
      - checkout
      - run:
          name: Build
          command: 'mvn clean install'
  test:
    docker:
      - image: maven:3.6-jdk-12
    steps:
      - checkout
      - run:
          name: Test
          command: 'mvn clean test'

workflows:
  version: 2
  default_workflow:
    jobs:
      - test
      - build