version: 2.1
jobs:
  build:
    docker:
      - image: maven:3.6-jdk-12
    steps:
      - checkout
      - run:
          name: Build
          command: 'mvn clean install'
  test:
    docker:
      - image: maven:3.6-jdk-12
    steps:
      - checkout
      - run:
          name: Test
          command: 'mvn clean test'
  docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Login at hub docker
          command: 'docker login -u $DOCKER_USER -p $DOCKER_PASS'
      - run:
          name: Generate docker image
          command: 'docker build . -t lucasfantacuci/apresentacao-circle-ci:${CIRCLE_BUILD_NUM}'
      - run:
          name: Tagging lastest build
          command: 'docker tag lucasfantacuci/apresentacao-circle-ci:${CIRCLE_BUILD_NUM} lucasfantacuci/apresentacao-circle-ci::latest'
      - run:
          name: Push latest to hub docker
          command: 'docker push lucasfantacuci/apresentacao-circle-ci:latest'
      - run:
          name: Push version to hub docker
          command: 'docker push lucasfantacuci/apresentacao-circle-ci:${CIRCLE_BUILD_NUM}'

workflows:
  version: 2
  default_workflow:
    jobs:
      - test
      - build
      - docker